stack-set: assumable-roles
capabilities:
  - CAPABILITY_NAMED_IAM
main-account-parameter: true
all-subaccounts: false
accounts:
  - 268875736166
  - 206924800932
  - 815637454826
max-concurrent-percentage: 100
regions:
  - ap-northeast-2
region: ap-northeast-2
tags:
  ValidateAllSubAccounts: true
  ValidateRegions: true
#vars:
#  DisabledIdentitiesServices:
#    - iam
parameters:
  AllowedRegions: ap-northeast-2
