stack-set: assumable-roles
capabilities:
  - CAPABILITY_NAMED_IAM
main-account-parameter: true
all-subaccounts: false
max-concurrent-percentage: 100
regions:
  - ap-northeast-2
region: ap-northeast-2
tags:
  ValidateAllSubAccounts: true
  ValidateRegions: ap-northeast-2
#vars:
#  DisabledIdentitiesServices:
#    - iam
parameters:
  AllowedRegions: ap-northeast-2
