stack-set: assumable-roles
capabilities:
  - CAPABILITY_NAMED_IAM
main-account-parameter: true
all-subaccounts: false
accounts:
  - 457258694188 
  - 765243622341 
  - 512758715856
  - 185302376606
  - 518471655024
  - 763718361067
  - 010382790647
max-concurrent-percentage: 100
regions:
  - ap-northeast-2
region: ap-northeast-2
tags:
  ValidateAllSubAccounts: true
  ValidateRegions: true
#vars:
#  DisabledIdentitiesServices:
#    - iam
parameters:
  AllowedRegions: ap-northeast-2
