{% set AWSSubAccounts = [ { 'Id': '206924800932', 'Email': 'atcl.skcc02@gmail.com'},
                          { 'Id': '815637454826', 'Email': 'atcl.skcc03@gmail.com'},] %}

Resources:
  GuardDutyDetector:
    Type: "AWS::GuardDuty::Detector"
    Properties:
      Enable: true

  {% for Account in AWSSubAccounts %}
  GuardDutyMember{{Account['Id']}}:
    DependsOn:
      - GuardDutyDetector
      {% if loop.index > 1 %}
      - GuardDutyMember{{AWSSubAccounts[loop.index-2]['Id']}}
      {% endif%}
    Type: "AWS::GuardDuty::Member"
    Properties:
      Status: "Invited"
      MemberId: "{{Account['Id']}}"
      Email: "{{Account['Email']}}"
      Message: "You are invited to enable Amazon Guardduty."
      DetectorId: !Ref GuardDutyDetector
      DisableEmailNotification: false
  {% endfor %}
