stack-set: guardduty-main
main-account: true
all-regions: false
excluded-regions:
  - eu-north-1
organization-variables: false
max-concurrent-percentage: 100
region: ap-northeast-2
tags:
  ValidateMainAccount: true
  ValidateAllRegions: false 
