stack-set: guardduty-main
main-account: true
#all-regions: false
regions:
  - ap-northeast-2
organization-variables: false
max-concurrent-percentage: 100
region: ap-northeast-2
tags:
  ValidateMainAccount: true
  ValidateAllRegions: true 
