stack-set: guardduty-main
main-account: true
#all-regions: true
excluded-regions:
  - eu-north-1
organization-variables: false
max-concurrent-percentage: 100
region: ap-northeast-2
tags:
  ValidateMainAccount: true
  ValidateAllRegions: true
