version: '2'
services:
  aws-baseline:
    build: ./toolbox
    volumes:
      - .:/app
      - ~/.aws/:/root/.aws
      - ./.bash_history:/root/.bash_history
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_PROFILE
      - AWS_DEFAULT_REGION=ap-northeast-2
      - AWS_SESSION_TOKEN
      - AWS_CONFIG_FILE=/root/.aws/config
