stack-set: config-rules
all-accounts: false
accounts:
  - 268875736166
  - 206924800932
  - 815637454826
#all-regions: true
excluded-regions:
  - eu-north-1
  - us-west-2
  - ap-south-1
  - sa-east-1
  - ap-southeast-1
  - eu-central-1
  - us-east-1
  - ap-northeast-1
  - eu-west-2
  - ap-southeast-2
  - eu-west-3
  - ca-central-1
  - us-east-2
  - eu-west-1
  - us-west-1
main-account-parameter: true
max-concurrent-percentage: 100
organization-variables: false
region: ap-northeast-2
vars:
  EnabledRegions:
    - ap-northeast-2
  EnabledConfigRules:
    EIP_ATTACHED: AWS::EC2::EIP
    INCOMING_SSH_DISABLED: AWS::EC2::SecurityGroup
    RDS_INSTANCE_PUBLIC_ACCESS_CHECK: AWS::RDS::DBInstance
    CLOUD_TRAIL_CLOUD_WATCH_LOGS_ENABLED: AWS::CloudTrail::Trail
    VPC_FLOW_LOGS_ENABLED: AWS::EC2::VPC
    S3_BUCKET_PUBLIC_READ_PROHIBITED: ['AWS::S3::Bucket', 'AWS::S3::AccountPublicAccessBlock']
    S3_BUCKET_PUBLIC_WRITE_PROHIBITED: ['AWS::S3::Bucket', 'AWS::S3::AccountPublicAccessBlock']
capabilities:
  - CAPABILITY_IAM
tags:
  ValidateAllAccounts: true
  ValidateAllRegions: false
parameters:
  GlobalConfigRegion: ap-northeast-2

# 참조: https://docs.aws.amazon.com/config/latest/developerguide/vpc-flow-logs-enabled.html