stack-set: guardduty-member
max-concurrent-percentage: 100
accounts:
  - 457258694188 
  - 512758715856
  - 185302376606
  - 518471655024
  - 763718361067
all-regions: true
#regions:
#  - ap-northeast-2
excluded-regions:
  - eu-north-1
main-account-parameter: true
region: ap-northeast-2
tags:
  ValidateAllSubAccounts: true
  ValidateAllRegions: true
