stack: vpc
stack-set: vpc
vars:
  AvailabilityZones: 3
# Example Endpoints for deploying an ECS Cluster
  GatewayEndpoints:
    - s3
  InterfaceEndpoints:
    - monitoring
    - logs
    - ecs
    - ecs-agent
    - ecs-telemetry
    - ecr.dkr
    - ecr.api
    - cloudformation
    - ssm
  AccountCIDR:
    268875736166:
      "ap-northeast-2": 10.1.0.0/16
parameters:
  PrivateNatGateway: all
all-subaccounts: false
accounts:
  - 268875736166
regions:
  - ap-northeast-2
max-concurrent-percentage: 100
tags:
  ValidateAllSubAccounts: 'true'
  ValidateRegions: ap-northeast-2
capabilities:
  - CAPABILITY_IAM
main-account-parameter: true
region: ap-northeast-2
