stack-set: auditing-configuration
capabilities:
  - CAPABILITY_IAM
#all-accounts: false
accounts:
  - 140499857323
  - 980637231723
  - 543945541886
#all-regions: false
#excluded-regions:
#  - eu-north-1
regions:
  - ap-northeast-2
main-account-parameter: true
max-concurrent-percentage: 100
region: ap-northeast-2
tags:
  ValidateAllAccounts: true
  ValidateAllRegions: true
parameters:
  GlobalConfigRegion: ap-northeast-2
