stack-set: auditing-configuration
capabilities:
  - CAPABILITY_IAM
#all-accounts: false
accounts:
  - 010382790647
  - 457258694188 
  - 512758715856
  - 185302376606
  - 518471655024
  - 763718361067
all-regions: false
excluded-regions:
  - eu-north-1
main-account-parameter: true
max-concurrent-percentage: 100
region: ap-northeast-2
tags:
  ValidateAllAccounts: true
  ValidateAllRegions: true
parameters:
  GlobalConfigRegion: ap-northeast-2
