stack-set: auditing-configuration
capabilities:
  - CAPABILITY_IAM
#all-accounts: false
accounts:
  - 037729278610
  - 751659651428
all-regions: false
excluded-regions:
  - eu-north-1
main-account-parameter: true
max-concurrent-percentage: 100
region: ap-northeast-2
tags:
  ValidateAllAccounts: true
  ValidateAllRegions: true
parameters:
  GlobalConfigRegion: ap-northeast-2
