stack: password-policy
stack-set: password-policy
all-accounts: true
max-concurrent-percentage: 100
regions:
  - ap-northeast-2
region: ap-northeast-2
capabilities:
  - CAPABILITY_IAM
tags:
  ValidateAllAccounts: true
  ValidateRegions: ap-northeast-2
