stack: password-policy
stack-set: password-policy
#all-accounts: false
max-concurrent-percentage: 100
accounts:
  - 140499857323
  - 980637231723
  - 543945541886
regions:
  - ap-northeast-2
region: ap-northeast-2
capabilities:
  - CAPABILITY_IAM
tags:
  ValidateAllAccounts: true
  ValidateRegions: ap-northeast-2
