stack-set: stack-set-execution-role
execution-role-name: OrganizationAccountAccessRole
capabilities:
  - CAPABILITY_NAMED_IAM
main-account-parameter: true
max-concurrent-percentage: 100
all-subaccounts: true
regions:
  - ap-northeast-2
region: ap-northeast-2
tags:
  ValidateAllSubAccounts: true
  ValidateRegions: ap-northeast-2
